// Generated by CoffeeScript 1.6.2
var updateTime;

updateTime = function() {
  var now;

  now = new Date();
  return $(".info").each(function() {
    var info;

    info = $(this);
    return info.text("Built " + (humanizeDate(now, items[currentBranch][info.attr("id")].date.raw)));
  });
};

$(document).ready(function() {
  return window.setInterval(updateTime, 60000);
});
